### ISSUE TITLE
Caractéristique / choix du joueur

### ISSUE THREAD

**Issue by VilcCasty** [Wurst-Devs/wurst-quest#1]
Nom
Race
Class
Level
Stats *X
HP max / current
Mana max / current
Etat (empoisonnée  / fatigué / ...)
Equipement *X
Sort *X
Inventaire *X
Quetes active (historique ? )
DAT BIG PLOT
Nombre de chaque monstre vaincu ? (j'aime bien les stats)

3 états
- ville
- recherche de combat
- combat

task "repos" où on recharge l'énergie, la vie, les sorts etc

**Comment by Klemek** [comment]
in english please
